from enum import Enum

class Errors(Enum):
    CART_DIMS_ERROR = "Attempting to change already defined grid size"
    COORD_ERROR = "COORD data size must be 6*(NX+1)*(NY+1)"
    ZCORN_ERROR = "ZCORN data size must be 2*NX*2*NY*2*NZ"
    PORO_ERROR = "PORO data size must be NX*NY*NZ"
    PERMX_ERROR = "PERMX data size must be NX*NY*NZ"
    PERMY_ERROR = "PERMY data size must be NX*NY*NZ"
    PERMZ_ERROR = "PERMZ data size must be NX*NY*NZ"
    ACTNUM_ERROR = "ACTNUM data size must be NX*NY*NZ"
    SO_ERROR = "SO data size must be NX*NY*NZ"
    GRID_NOT_DEFINED_ERROR = "The grid is not defined!"
    CHECK_DIM_ERRROR = "GRDECL keyword {} found before dimension specification"
    LOAD_CELL_DATA_ERROR = "{} data size must be NX*NY*NZ"
    TOPS_ERROR = "TOPS data size must be NX*NY*NZ"
    DX_ERROR = "DX data size must be NX*NY*NZ"
    DY_ERROR = "DY data size must be NX*NY*NZ"
    DZ_ERROR = "DZ data size must be NX*NY*NZ"
    FILE_NOT_FOUND_ERROR = "Can't open the file {}"
    EOF_ERROR = "EOF when reading a line"